# EssentiallyHelp - v1.0 Copied from Essentials

#general options
options:
  showplugins: true
  sorted: false

messages:
# Display local-server join message
  join: true
# Display local-server quit message
  quit: true
# Message to send to user on first-join
  welcome:
    - '&6Welcome &c{PLAYER}&6!'
    - '&6Use &c/info&6 for guides and other information'
    - '&6Use &c/help&6 for help using commands'
    - '&6Players online:&c {ONLINE} &6- World time:&c {WORLDTIME12}&r'

#manually added commands:
#commands:
#  example: 'This is an example description'

info:
  help:
    permission: '*'
    text:
      - '&rInformation available at:'
      - '&f[&6http://github.com/MCShovel/EssentiallyHelp&f]&r'
      - '&r'
      - 'Use &c/info reload&r after editing the info section'
      - 'or &c/help reload&r after editing the help section'
      - '&r'
      - 'Adding permission nodes will restrict who can see a'
      - 'particular section.'
  colors:
    text:
      - '&6 Minecraft Color Codes:'
      - '&r[& 0] &0 Black              &r[& 8] &8 Dark Gray'
      - '&r[& 1] &1 Dark Blue         &r[& 9] &9 Blue'
      - '&r[& 2] &2 Dark Green       &r[& a] &a Green'
      - '&r[& 3] &3 Dark Aqua        &r[& b] &b Aqua'
      - '&r[& 4] &4 Dark Red          &r[& c] &c Red'
      - '&r[& 5] &5 Dark Purple      &r[& d] &d Light Purple'
      - '&r[& 6] &6 Gold                &r[& e] &e Yellow'
      - '&r[& 7] &7 Gray               &r[& f] &f White'
      - '&6 Minecraft Format Codes:'
      - '&r[& k]  &kObfuscated&r         [& l] &l Bold'
      - '&r[& m]  &mStrikethrough&r      [& n] &n Underline'
      - '&r[& n] &o Italic                 &r[& r] &r Reset'

#true to disable the display of specific commands or entire plugin contents
disabled:
  plugin:
    essentiallyhelp: false
  command:
    info: false

#formatting of help output
formatting:
  helpMatching: '&6Commands  matching "&c{name}&6":'
  helpPlugin: '&4{name}&f: Plugin Help: /help {lname}'
  helpFrom: '&6Commands from {name}:'
  helpLine: '&6/{name}&f: {desc}'
  readNextPage: '&6Type&c /{name} {page} &6to read the next page.'
  infoChapterPages: '&e ---- &6{content} &e--&6 Page &c{page}&6 of &c{pages} &e----'
  infoPages: '&e ---- &6{content} &e--&6 Page &c{page}&6 of &c{pages} &e----'
  infoChapter: '&6Select chapter:'
  infoUnknownChapter: '&4Unknown chapter.'
  noAccessToTopic: '&cYou do not have access to that topic.'
  topicNotFound: '&6Topic &c{topic}&6 not found.'
  topicList: '&6Topics&f: {topics}'
