name: EssentiallyHelp
main: com.steamcraftmc.EssentiallyHelp.MainPlugin
version: '1.0'
author: rknapp
load: startup
commands:
  help:
    description: Get help for the commands you have available.
    usage: /help [topic/filter] [page number]
    permission: essentials.help
    permission-message: 'ยง4You do not have permission to perform this action.'
    default: true
  info:
    description: Provides general information for this server.
    usage: /info [topic] [page number]
    permission: essentials.info
    permission-message: 'ยง4You do not have permission to perform this action.'
    default: true

